import type { DiffResult } from "../core/types.js";

export function reportMarkdown(results: DiffResult[]): string {
  const lines: string[] = [];

  lines.push("## MCP Sentinel - Schema Drift Report");
  lines.push("");

  const clean = results.filter((r) => r.status === "CLEAN");
  const drifted = results.filter((r) => r.status === "DRIFT");

  if (drifted.length === 0 && clean.length > 0) {
    lines.push("No schema drift detected across " + clean.length + " server(s).");
    return lines.join("\n");
  }

  lines.push("### Summary");
  lines.push("");
  lines.push("| Server | Status | Changes |");
  lines.push("|--------|--------|---------|");
  for (const r of results) {
    const icon = r.status === "CLEAN" ? "white_check_mark" : r.severity === "MAJOR" ? "red_circle" : r.severity === "MINOR" ? "warning" : "blue_circle";
    lines.push("| " + r.server + " | " + ("`" + r.status + "` " + icon) + " | " + r.changes.length + " |");
  }
  lines.push("");

  for (const result of drifted) {
    const icon = result.severity === "MAJOR" ? "red_circle" : result.severity === "MINOR" ? "warning" : "blue_circle";
    lines.push("### " + icon + " " + result.server + " (" + result.severity + ")");
    lines.push("");

    for (const change of result.changes) {
      const prefix = change.severity === "MAJOR" ? "red_circle" : change.severity === "MINOR" ? "warning" : "blue_circle";
      lines.push("#### " + prefix + " " + change.ruleId + ": " + change.summary);
      lines.push("");
      lines.push(change.detail);
      if (change.before !== undefined) {
        lines.push("");
        lines.push("<details><summary>Before / After</summary>");
        lines.push("");
        lines.push("**Before:** `" + JSON.stringify(change.before).slice(0, 200) + "`");
        lines.push("");
        if (change.after !== null) {
          lines.push("**After:** `" + JSON.stringify(change.after).slice(0, 200) + "`");
        }
        lines.push("");
        lines.push("</details>");
      }
      lines.push("");
    }

    if (result.addedTools.length > 0) {
      lines.push("*New tools:* " + result.addedTools.map((t) => "`" + t + "`").join(", "));
      lines.push("");
    }
    if (result.removedTools.length > 0) {
      lines.push("*Removed tools:* " + result.removedTools.map((t) => "`" + t + "`").join(", "));
      lines.push("");
    }
  }

  const majors = results.reduce((sum, r) => sum + r.changes.filter((c) => c.severity === "MAJOR").length, 0);
  const minors = results.reduce((sum, r) => sum + r.changes.filter((c) => c.severity === "MINOR").length, 0);
  const patches = results.reduce((sum, r) => sum + r.changes.filter((c) => c.severity === "PATCH").length, 0);
  const total = majors + minors + patches;

  lines.push("---");
  lines.push("");
  lines.push("*Generated by [MCP Sentinel](https://github.com/mcp-sentinel/sentinel) v0.1.0*");
  lines.push("  Total: " + total + " change(s) | " + majors + " MAJOR | " + minors + " MINOR | " + patches + " PATCH");

  return lines.join("\n");
}
